"""Compare our momentum quartiles against the author's reference quartiles.

Inputs:
  - data/momentum/{signal}/holdings/{YYYY-MM}.json  (ours)
  - agent_context/reference_quartiles.json           (parsed from blog export)

Both label Q1 = top momentum .. Q4 = bottom (same convention).

Two views, because the universes differ (ours is survivorship-free / larger):
  1. Raw membership diff per quartile (Jaccard) — practical portfolio divergence.
  2. Quartile agreement on the universe INTERSECTION — a confusion matrix
     (our quartile x ref quartile) isolating ranking disagreement from universe
     differences. Diagonal = agreement; asymmetric off-diagonal = directional bias.

Output: agent_context/reference_quartiles_diff.md. One-shot.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SIGNAL = "curve_fit"
OURS_DIR = ROOT / "data" / "momentum" / SIGNAL / "holdings"
REF_FILE = ROOT / "agent_context" / "reference_quartiles.json"
OUT = ROOT / "agent_context" / "reference_quartiles_diff.md"

QS = ("Q1", "Q2", "Q3", "Q4")


def _load(path: Path) -> dict[str, list[str]]:
    return json.loads(path.read_text(encoding="utf-8"))


def _quartile_of(holdings: dict[str, list[str]]) -> dict[str, int]:
    return {tk: i for i, q in enumerate(QS, 1) for tk in holdings[q]}


def _jaccard(a: set[str], b: set[str]) -> float:
    u = a | b
    return len(a & b) / len(u) if u else 1.0


def main() -> None:
    ref_index = _load(REF_FILE)
    months = sorted(set(ref_index) & {p.stem for p in OURS_DIR.glob("*.json")})

    rows: list[dict] = []
    confusion = [[0] * 4 for _ in range(4)]  # confusion[our-1][ref-1]
    q1_into = [0, 0, 0, 0]  # where ref-Q1 names land in our quartiles (on intersection)

    for m in months:
        ref = {q: ref_index[m][q] for q in QS}
        our = _load(OURS_DIR / f"{m}.json")
        ref_q = _quartile_of(ref)
        our_q = _quartile_of(our)
        inter = set(ref_q) & set(our_q)

        for tk in inter:
            confusion[our_q[tk] - 1][ref_q[tk] - 1] += 1
            if ref_q[tk] == 1:
                q1_into[our_q[tk] - 1] += 1

        agree = sum(1 for tk in inter if ref_q[tk] == our_q[tk])
        within1 = sum(1 for tk in inter if abs(ref_q[tk] - our_q[tk]) <= 1)
        rows.append(
            {
                "month": m,
                "ref_u": len(ref_q),
                "our_u": len(our_q),
                "inter": len(inter),
                "jac": {q: _jaccard(set(ref[q]), set(our[q])) for q in QS},
                "agree": agree / len(inter) if inter else 0.0,
                "within1": within1 / len(inter) if inter else 0.0,
            }
        )

    _write_report(rows, confusion, q1_into)
    print(f"compared {len(months)} months: {months[0]} -> {months[-1]}")
    print(f"wrote {OUT}")


def _write_report(rows: list[dict], confusion: list[list[int]], q1_into: list[int]) -> None:
    n = len(rows)
    avg_jac = {q: sum(r["jac"][q] for r in rows) / n for q in QS}
    total_inter = sum(sum(c) for c in confusion)
    diag = sum(confusion[i][i] for i in range(4))
    within1 = sum(confusion[i][j] for i in range(4) for j in range(4) if abs(i - j) <= 1)

    lines: list[str] = []
    lines.append("# Our momentum quartiles vs author reference — diff")
    lines.append("")
    lines.append(
        f"Signal `{SIGNAL}` vs `agent_context/reference_quartiles.json`. "
        f"{n} common months ({rows[0]['month']} → {rows[-1]['month']}). "
        "Both: Q1 = top momentum. Generated by `scripts/compare_reference_quartiles.py`."
    )
    lines.append("")
    lines.append("## Headline")
    lines.append("")
    agree_pct = diag / total_inter * 100
    lines.append(
        f"- Exact same-quartile agreement (on universe intersection): **{agree_pct:.1f}%**"
    )
    lines.append(f"- Within ±1 quartile: **{within1 / total_inter * 100:.1f}%**")
    lines.append(
        f"- Mean per-quartile Jaccard (raw membership): "
        f"Q1 **{avg_jac['Q1']:.2f}** · Q2 {avg_jac['Q2']:.2f} · "
        f"Q3 {avg_jac['Q3']:.2f} · Q4 **{avg_jac['Q4']:.2f}**"
    )
    lines.append("")
    lines.append(
        "## Confusion matrix — intersection only (rows = ours, cols = ref), row-normalized %"
    )
    lines.append("")
    lines.append(
        "Reads: of intersection names WE place in Qr, what quartile does the author assign?"
    )
    lines.append("")
    lines.append("| ours \\ ref | Q1 | Q2 | Q3 | Q4 | n |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for i in range(4):
        rs = sum(confusion[i]) or 1
        cells = " | ".join(f"{confusion[i][j] / rs * 100:.0f}" for j in range(4))
        lines.append(f"| Q{i + 1} | {cells} | {sum(confusion[i])} |")
    lines.append("")
    lines.append("## Where the author's Q1 (top-momentum) names land in OUR quartiles")
    lines.append("")
    tot = sum(q1_into) or 1
    lines.append("| ref Q1 → our | Q1 | Q2 | Q3 | Q4 |")
    lines.append("|---|---:|---:|---:|---:|")
    lines.append("| count | " + " | ".join(str(x) for x in q1_into) + " |")
    lines.append("| % | " + " | ".join(f"{x / tot * 100:.0f}" for x in q1_into) + " |")
    lines.append("")
    lines.append("## Per-month detail")
    lines.append("")
    lines.append("| month | ref_u | our_u | ∩ | J(Q1) | J(Q2) | J(Q3) | J(Q4) | agree% | ±1% |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in rows:
        j = r["jac"]
        lines.append(
            f"| {r['month']} | {r['ref_u']} | {r['our_u']} | {r['inter']} | "
            f"{j['Q1']:.2f} | {j['Q2']:.2f} | {j['Q3']:.2f} | {j['Q4']:.2f} | "
            f"{r['agree'] * 100:.0f} | {r['within1'] * 100:.0f} |"
        )
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
